import { img } from '../../load';

export default {
    flame: {
        sFrame: img('assets/bonuses/flame/flame.png'),
        varName: 'power',
        maxCount: 7,
        startCount: 1,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
        // probably:
    },
    extraBomb: {
        sFrame: img('assets/bonuses/extra_bomb/extra_bomb.png'),
        varName: 'maxBombCount',
        maxCount: 8,
        startCount: 1,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    rollers: {
        sFrame: img('assets/bonuses/rollers/rollers.png'),
        varName: 'rollers',
        maxCount: 4,
        startCount: 1,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    protect: {
        sFrame: img('assets/bonuses/protect/protect.png'),
        varName: 'protect',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    burnWall: {
        sFrame: img('assets/bonuses/burn_wall/burn_wall.png'),
        varName: 'burnWall',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    doubleBomb: {
        sFrame: img('assets/bonuses/double_bomb/double_bomb.png'),
        varName: 'doublBomb',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    radioBomb: {
        sFrame: img('assets/bonuses/radio_bomb/radio_bomb.png'),
        varName: 'radioBomb',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    throughBomb: {
        sFrame: img('assets/bonuses/through_bomb/through_bomb.png'),
        varName: 'throughBomb',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
    throughWall: {
        sFrame: img('assets/bonuses/through_wall/through_wall.png'),
        varName: 'throughWall',
        maxCount: 1,
        startCount: 0,
        width: 0.8,
        height: 0.8,
        rendWidth: 1,
        rendHeight: 1,
    },
};
